### ISSUE TITLE
TJMaxx Bug

### ISSUE THREAD

**Issue by kerrykimrusso** [kerrykimrusso/target-blank#31]
**URL** [https://tjmaxx.tjx.com/store/jump/product/holiday-gift-giving-gifts-for-women/Holiday-Tub-Of-Bath-Treats/1000245542?colorId=NS1003538&pos=1:1&N=835635021](https://tjmaxx.tjx.com/store/jump/product/holiday-gift-giving-gifts-for-women/Holiday-Tub-Of-Bath-Treats/1000245542?colorId=NS1003538&pos=1:1&N=835635021)

**Target URL:** any of the products

**Expected behavior:** open a new tab with the specific product page open
**Actual behavior:** opens the new tab but also opens in the current tab

**Comment by kerrykimrusso** [comment]
**Additional details:** clicking the quick look button on the product has the correct behavior, but clicking anywhere else on the product exhibits the undesired behavior described above.

**Comment by BeejLuig** [comment]
I created two fresh anchor tags on the TJMaxx page, one with an absolute path to another website and one relative path. My options are set to new-tab/new-tab. The absolute link opened in a new tab, and relative opened in the same tab.

Either way I'm not seeing the same buggy behavior as the native links on the website, which makes me think that there are likely event listeners on the anchor tags disrupting our listeners.

I propose that we permanently whitelist this page, or create a "blacklist" strategy that ignores sites like this by default and has some sort of indicating icon to show that our extension won't work. Since there is no current support for checking if event listeners exist on an element, nor is there support for blanket removing event listeners (it'll probably never happen), we don't really have a way to handle these types of pages.

**Comment by kerrykimrusso** [comment]
I think that adding a blacklist strategy and showing some sort of status to the user that our extension is disabled for it is a good way to go.

**Comment by kerrykimrusso** [comment]
Won't FIX.
